# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-05 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0002_auto_20180405_0329'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='users',
            field=models.ManyToManyField(related_name='quotes', to='quotations.User'),
        ),
    ]
