# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-05 03:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0003_quote_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='users',
            new_name='user',
        ),
    ]
