# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-05 04:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0004_auto_20180405_0342'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='user_favorited',
            field=models.ManyToManyField(related_name='favorites', to='quotations.User'),
        ),
    ]
